// Code generated by go-swagger; DO NOT EDIT.

package dashboards_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDashboardParams creates a new GetDashboardParams object
// with the default values initialized.
func NewGetDashboardParams() *GetDashboardParams {
	var ()
	return &GetDashboardParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDashboardParamsWithTimeout creates a new GetDashboardParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDashboardParamsWithTimeout(timeout time.Duration) *GetDashboardParams {
	var ()
	return &GetDashboardParams{

		timeout: timeout,
	}
}

// NewGetDashboardParamsWithContext creates a new GetDashboardParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDashboardParamsWithContext(ctx context.Context) *GetDashboardParams {
	var ()
	return &GetDashboardParams{

		Context: ctx,
	}
}

// NewGetDashboardParamsWithHTTPClient creates a new GetDashboardParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDashboardParamsWithHTTPClient(client *http.Client) *GetDashboardParams {
	var ()
	return &GetDashboardParams{
		HTTPClient: client,
	}
}

/*GetDashboardParams contains all the parameters to send to the API endpoint
for the get dashboard operation typically these are written to a http.Request
*/
type GetDashboardParams struct {

	/*IDOrName*/
	IDOrName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get dashboard params
func (o *GetDashboardParams) WithTimeout(timeout time.Duration) *GetDashboardParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get dashboard params
func (o *GetDashboardParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get dashboard params
func (o *GetDashboardParams) WithContext(ctx context.Context) *GetDashboardParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get dashboard params
func (o *GetDashboardParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get dashboard params
func (o *GetDashboardParams) WithHTTPClient(client *http.Client) *GetDashboardParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get dashboard params
func (o *GetDashboardParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIDOrName adds the iDOrName to the get dashboard params
func (o *GetDashboardParams) WithIDOrName(iDOrName string) *GetDashboardParams {
	o.SetIDOrName(iDOrName)
	return o
}

// SetIDOrName adds the idOrName to the get dashboard params
func (o *GetDashboardParams) SetIDOrName(iDOrName string) {
	o.IDOrName = iDOrName
}

// WriteToRequest writes these params to a swagger request
func (o *GetDashboardParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id_or_name
	if err := r.SetPathParam("id_or_name", o.IDOrName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
