// Code generated by go-swagger; DO NOT EDIT.

package semaphore_secrets_v1beta_secrets_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/semaphoreci/cli/api/models"
)

// ListSecretsReader is a Reader for the ListSecrets structure.
type ListSecretsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListSecretsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListSecretsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListSecretsOK creates a ListSecretsOK with default headers values
func NewListSecretsOK() *ListSecretsOK {
	return &ListSecretsOK{}
}

/*ListSecretsOK handles this case with default header values.

(empty)
*/
type ListSecretsOK struct {
	Payload *models.SemaphoreSecretsV1betaListSecretsResponse
}

func (o *ListSecretsOK) Error() string {
	return fmt.Sprintf("[GET /api/v1beta/secrets][%d] listSecretsOK  %+v", 200, o.Payload)
}

func (o *ListSecretsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SemaphoreSecretsV1betaListSecretsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
