// Code generated by go-swagger; DO NOT EDIT.

package semaphore_secrets_v1beta_secrets_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListSecretsParams creates a new ListSecretsParams object
// with the default values initialized.
func NewListSecretsParams() *ListSecretsParams {
	var (
		orderDefault = string("BY_NAME_ASC")
	)
	return &ListSecretsParams{
		Order: &orderDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewListSecretsParamsWithTimeout creates a new ListSecretsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListSecretsParamsWithTimeout(timeout time.Duration) *ListSecretsParams {
	var (
		orderDefault = string("BY_NAME_ASC")
	)
	return &ListSecretsParams{
		Order: &orderDefault,

		timeout: timeout,
	}
}

// NewListSecretsParamsWithContext creates a new ListSecretsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListSecretsParamsWithContext(ctx context.Context) *ListSecretsParams {
	var (
		orderDefault = string("BY_NAME_ASC")
	)
	return &ListSecretsParams{
		Order: &orderDefault,

		Context: ctx,
	}
}

// NewListSecretsParamsWithHTTPClient creates a new ListSecretsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListSecretsParamsWithHTTPClient(client *http.Client) *ListSecretsParams {
	var (
		orderDefault = string("BY_NAME_ASC")
	)
	return &ListSecretsParams{
		Order:      &orderDefault,
		HTTPClient: client,
	}
}

/*ListSecretsParams contains all the parameters to send to the API endpoint
for the list secrets operation typically these are written to a http.Request
*/
type ListSecretsParams struct {

	/*Order*/
	Order *string
	/*PageSize*/
	PageSize *int32
	/*PageToken*/
	PageToken *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list secrets params
func (o *ListSecretsParams) WithTimeout(timeout time.Duration) *ListSecretsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list secrets params
func (o *ListSecretsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list secrets params
func (o *ListSecretsParams) WithContext(ctx context.Context) *ListSecretsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list secrets params
func (o *ListSecretsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list secrets params
func (o *ListSecretsParams) WithHTTPClient(client *http.Client) *ListSecretsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list secrets params
func (o *ListSecretsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrder adds the order to the list secrets params
func (o *ListSecretsParams) WithOrder(order *string) *ListSecretsParams {
	o.SetOrder(order)
	return o
}

// SetOrder adds the order to the list secrets params
func (o *ListSecretsParams) SetOrder(order *string) {
	o.Order = order
}

// WithPageSize adds the pageSize to the list secrets params
func (o *ListSecretsParams) WithPageSize(pageSize *int32) *ListSecretsParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the list secrets params
func (o *ListSecretsParams) SetPageSize(pageSize *int32) {
	o.PageSize = pageSize
}

// WithPageToken adds the pageToken to the list secrets params
func (o *ListSecretsParams) WithPageToken(pageToken *string) *ListSecretsParams {
	o.SetPageToken(pageToken)
	return o
}

// SetPageToken adds the pageToken to the list secrets params
func (o *ListSecretsParams) SetPageToken(pageToken *string) {
	o.PageToken = pageToken
}

// WriteToRequest writes these params to a swagger request
func (o *ListSecretsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Order != nil {

		// query param order
		var qrOrder string
		if o.Order != nil {
			qrOrder = *o.Order
		}
		qOrder := qrOrder
		if qOrder != "" {
			if err := r.SetQueryParam("order", qOrder); err != nil {
				return err
			}
		}

	}

	if o.PageSize != nil {

		// query param page_size
		var qrPageSize int32
		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt32(qrPageSize)
		if qPageSize != "" {
			if err := r.SetQueryParam("page_size", qPageSize); err != nil {
				return err
			}
		}

	}

	if o.PageToken != nil {

		// query param page_token
		var qrPageToken string
		if o.PageToken != nil {
			qrPageToken = *o.PageToken
		}
		qPageToken := qrPageToken
		if qPageToken != "" {
			if err := r.SetQueryParam("page_token", qPageToken); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
