// Code generated by go-swagger; DO NOT EDIT.

package semaphore_secrets_v1beta_secrets_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/renderedtext/sem/api/models"
)

// UpdateSecretReader is a Reader for the UpdateSecret structure.
type UpdateSecretReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateSecretReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdateSecretOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateSecretOK creates a UpdateSecretOK with default headers values
func NewUpdateSecretOK() *UpdateSecretOK {
	return &UpdateSecretOK{}
}

/*UpdateSecretOK handles this case with default header values.

(empty)
*/
type UpdateSecretOK struct {
	Payload *models.SemaphoreSecretsV1betaSecret
}

func (o *UpdateSecretOK) Error() string {
	return fmt.Sprintf("[PATCH /api/v1beta/secrets/{secret_id_or_name}][%d] updateSecretOK  %+v", 200, o.Payload)
}

func (o *UpdateSecretOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SemaphoreSecretsV1betaSecret)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
