package cmd

import (
	"fmt"

	client "github.com/semaphoreci/cli/api/client"
	"github.com/semaphoreci/cli/cmd/utils"
	"github.com/spf13/cobra"
)

var logsCmd = &cobra.Command{
	Use:   "logs [JOB ID]",
	Short: "Display logs generated by a job.",
	Long:  ``,
	Args:  cobra.ExactArgs(1),

	Run: func(cmd *cobra.Command, args []string) {
		id := args[0]

		c := client.NewLogsV1AlphaApi()
		logs, err := c.Get(id)
		utils.Check(err)

		for _, e := range logs.Events {
			if e.Type == "cmd_output" {
				fmt.Println(e.Output)
			}

			if e.Type == "cmd_started" {
				fmt.Printf("\n\x1b[33m✻ %s\x1b[0m\n", e.Directive)
			}

			if e.Type == "cmd_finished" {
				fmt.Printf("\x1b[33mexit status: %d\x1b[0m\n", e.ExitCode)
			}

			if e.Type == "job_finished" {
				if e.JobResult == "passed" {
					fmt.Printf("\n\n\x1b[32mJob %s.\x1b[0m\n", e.JobResult)
				}

				if e.JobResult == "failed" {
					fmt.Printf("\n\n\x1b[31mJob %s.\x1b[0m\n", e.JobResult)
				}
			}
		}
	},
}

func init() {
	RootCmd.AddCommand(logsCmd)
}
