#!/bin/sh

unameOut="$(uname -a)"

case "${unameOut}" in
    Linux*)
      os=linux
      ;;

    Darwin*)
      os=linux
      ;;

    *)
      echo "Unsupported operating system."
      exit 1
      ;;
esac

case "${unameOut}" in
     *x86_64*)
      arch=amd64
      ;;

     *386*)
      arch=386
      ;;

    *)
      echo "Unsupported architecture."
      exit 1
      ;;
esac

wget "https://storage.googleapis.com/sem-cli-releases/stable-${os}-${arch}.tar.gz" -O /tmp/sem.tar.gz

if [ ! -f /tmp/sem.tar.gz ]; then
  echo "Failed to fetch sem binary"
  exit 1
fi

cd /tmp
tar -xzvf sem.tar.gz
sudo chmod +x sem
sudo mv sem /usr/local/bin/

echo ""
echo "Semaphore CLI installed."
