// Code generated by go-swagger; DO NOT EDIT.

package semaphore_dashboards_v1alpha_dashboards_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/semaphoreci/cli/api/models"
)

// CreateDashboardReader is a Reader for the CreateDashboard structure.
type CreateDashboardReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateDashboardReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateDashboardOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewCreateDashboardDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateDashboardOK creates a CreateDashboardOK with default headers values
func NewCreateDashboardOK() *CreateDashboardOK {
	return &CreateDashboardOK{}
}

/*CreateDashboardOK handles this case with default header values.

(empty)
*/
type CreateDashboardOK struct {
	Payload *models.SemaphoreDashboardsV1alphaDashboard
}

func (o *CreateDashboardOK) Error() string {
	return fmt.Sprintf("[POST /api/v1alpha/dashboards][%d] createDashboardOK  %+v", 200, o.Payload)
}

func (o *CreateDashboardOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SemaphoreDashboardsV1alphaDashboard)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateDashboardDefault creates a CreateDashboardDefault with default headers values
func NewCreateDashboardDefault(code int) *CreateDashboardDefault {
	return &CreateDashboardDefault{
		_statusCode: code,
	}
}

/*CreateDashboardDefault handles this case with default header values.

error
*/
type CreateDashboardDefault struct {
	_statusCode int

	Payload string
}

// Code gets the status code for the create dashboard default response
func (o *CreateDashboardDefault) Code() int {
	return o._statusCode
}

func (o *CreateDashboardDefault) Error() string {
	return fmt.Sprintf("[POST /api/v1alpha/dashboards][%d] CreateDashboard default  %+v", o._statusCode, o.Payload)
}

func (o *CreateDashboardDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
