// Code generated by go-swagger; DO NOT EDIT.

package semaphore_dashboards_v1alpha_dashboards_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/semaphoreci/cli/api/models"
)

// NewUpdateDashboardParams creates a new UpdateDashboardParams object
// with the default values initialized.
func NewUpdateDashboardParams() *UpdateDashboardParams {
	var ()
	return &UpdateDashboardParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateDashboardParamsWithTimeout creates a new UpdateDashboardParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateDashboardParamsWithTimeout(timeout time.Duration) *UpdateDashboardParams {
	var ()
	return &UpdateDashboardParams{

		timeout: timeout,
	}
}

// NewUpdateDashboardParamsWithContext creates a new UpdateDashboardParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateDashboardParamsWithContext(ctx context.Context) *UpdateDashboardParams {
	var ()
	return &UpdateDashboardParams{

		Context: ctx,
	}
}

// NewUpdateDashboardParamsWithHTTPClient creates a new UpdateDashboardParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateDashboardParamsWithHTTPClient(client *http.Client) *UpdateDashboardParams {
	var ()
	return &UpdateDashboardParams{
		HTTPClient: client,
	}
}

/*UpdateDashboardParams contains all the parameters to send to the API endpoint
for the update dashboard operation typically these are written to a http.Request
*/
type UpdateDashboardParams struct {

	/*Body*/
	Body *models.SemaphoreDashboardsV1alphaDashboard
	/*IDOrName*/
	IDOrName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update dashboard params
func (o *UpdateDashboardParams) WithTimeout(timeout time.Duration) *UpdateDashboardParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update dashboard params
func (o *UpdateDashboardParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update dashboard params
func (o *UpdateDashboardParams) WithContext(ctx context.Context) *UpdateDashboardParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update dashboard params
func (o *UpdateDashboardParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update dashboard params
func (o *UpdateDashboardParams) WithHTTPClient(client *http.Client) *UpdateDashboardParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update dashboard params
func (o *UpdateDashboardParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update dashboard params
func (o *UpdateDashboardParams) WithBody(body *models.SemaphoreDashboardsV1alphaDashboard) *UpdateDashboardParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update dashboard params
func (o *UpdateDashboardParams) SetBody(body *models.SemaphoreDashboardsV1alphaDashboard) {
	o.Body = body
}

// WithIDOrName adds the iDOrName to the update dashboard params
func (o *UpdateDashboardParams) WithIDOrName(iDOrName string) *UpdateDashboardParams {
	o.SetIDOrName(iDOrName)
	return o
}

// SetIDOrName adds the idOrName to the update dashboard params
func (o *UpdateDashboardParams) SetIDOrName(iDOrName string) {
	o.IDOrName = iDOrName
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateDashboardParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id_or_name
	if err := r.SetPathParam("id_or_name", o.IDOrName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
