// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// SemaphoreDashboardsV1alphaEmpty semaphore dashboards v1alpha empty
// swagger:model SemaphoreDashboardsV1alphaEmpty
type SemaphoreDashboardsV1alphaEmpty interface{}
