// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// SemaphoreSecretsV1betaEmpty semaphore secrets v1beta empty
// swagger:model SemaphoreSecretsV1betaEmpty
type SemaphoreSecretsV1betaEmpty interface{}
