// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

	import (
yaml "gopkg.in/yaml.v2"
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SemaphoreDashboardsV1alphaDashboardSpec semaphore dashboards v1alpha dashboard spec
// swagger:model SemaphoreDashboardsV1alphaDashboardSpec
type SemaphoreDashboardsV1alphaDashboardSpec struct {

	// widgets
	Widgets []*SemaphoreDashboardsV1alphaDashboardSpecWidget `json:"widgets"`
}

// Validate validates this semaphore dashboards v1alpha dashboard spec
func (m *SemaphoreDashboardsV1alphaDashboardSpec) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateWidgets(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SemaphoreDashboardsV1alphaDashboardSpec) validateWidgets(formats strfmt.Registry) error {

	if swag.IsZero(m.Widgets) { // not required
		return nil
	}

	for i := 0; i < len(m.Widgets); i++ {
		if swag.IsZero(m.Widgets[i]) { // not required
			continue
		}

		if m.Widgets[i] != nil {
			if err := m.Widgets[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("widgets" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SemaphoreDashboardsV1alphaDashboardSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SemaphoreDashboardsV1alphaDashboardSpec) UnmarshalBinary(b []byte) error {
	var res SemaphoreDashboardsV1alphaDashboardSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}


  // MmarshalYaml interface implementation
  func (m *SemaphoreDashboardsV1alphaDashboardSpec) MarshalYaml() ([]byte, error) {
    return yaml.Marshal(m)
  }

  

  // MmarshalYaml interface implementation
  func (m *SemaphoreDashboardsV1alphaDashboardSpec) UnmarshalYaml(b []byte) error {
    var res SemaphoreDashboardsV1alphaDashboardSpec

    err := yaml.UnmarshalStrict(b, &res)

    if err != nil {
      return err
    }

    *m = res
    return nil
  }

  