// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

	import (
yaml "gopkg.in/yaml.v2"
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// SemaphoreSecretsV1betaSecretFile semaphore secrets v1beta secret file
// swagger:model SemaphoreSecretsV1betaSecretFile
type SemaphoreSecretsV1betaSecretFile struct {

	// content
	Content string `json:"content,omitempty"`

	// path
	Path string `json:"path,omitempty"`
}

// Validate validates this semaphore secrets v1beta secret file
func (m *SemaphoreSecretsV1betaSecretFile) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SemaphoreSecretsV1betaSecretFile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SemaphoreSecretsV1betaSecretFile) UnmarshalBinary(b []byte) error {
	var res SemaphoreSecretsV1betaSecretFile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}


  // MmarshalYaml interface implementation
  func (m *SemaphoreSecretsV1betaSecretFile) MarshalYaml() ([]byte, error) {
    return yaml.Marshal(m)
  }

  

  // MmarshalYaml interface implementation
  func (m *SemaphoreSecretsV1betaSecretFile) UnmarshalYaml(b []byte) error {
    var res SemaphoreSecretsV1betaSecretFile

    err := yaml.UnmarshalStrict(b, &res)

    if err != nil {
      return err
    }

    *m = res
    return nil
  }

  