// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// SemaphoreSecretsV1betaSecretEnvVar semaphore secrets v1beta secret env var
// swagger:model SemaphoreSecretsV1betaSecretEnvVar
type SemaphoreSecretsV1betaSecretEnvVar struct {

	// name
	Name string `json:"name,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this semaphore secrets v1beta secret env var
func (m *SemaphoreSecretsV1betaSecretEnvVar) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SemaphoreSecretsV1betaSecretEnvVar) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SemaphoreSecretsV1betaSecretEnvVar) UnmarshalBinary(b []byte) error {
	var res SemaphoreSecretsV1betaSecretEnvVar
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
