// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// SemaphoreSecretsV1betaSecretMetadata semaphore secrets v1beta secret metadata
// swagger:model SemaphoreSecretsV1betaSecretMetadata
type SemaphoreSecretsV1betaSecretMetadata struct {

	// create time
	CreateTime string `json:"create_time,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// update time
	UpdateTime string `json:"update_time,omitempty"`
}

// Validate validates this semaphore secrets v1beta secret metadata
func (m *SemaphoreSecretsV1betaSecretMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SemaphoreSecretsV1betaSecretMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SemaphoreSecretsV1betaSecretMetadata) UnmarshalBinary(b []byte) error {
	var res SemaphoreSecretsV1betaSecretMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
