// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

	import (
yaml "gopkg.in/yaml.v2"
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// SemaphoreDashboardsV1alphaDashboardMetadata semaphore dashboards v1alpha dashboard metadata
// swagger:model SemaphoreDashboardsV1alphaDashboardMetadata
type SemaphoreDashboardsV1alphaDashboardMetadata struct {

	// create time
	CreateTime string `json:"create_time,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// update time
	UpdateTime string `json:"update_time,omitempty"`
}

// Validate validates this semaphore dashboards v1alpha dashboard metadata
func (m *SemaphoreDashboardsV1alphaDashboardMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SemaphoreDashboardsV1alphaDashboardMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SemaphoreDashboardsV1alphaDashboardMetadata) UnmarshalBinary(b []byte) error {
	var res SemaphoreDashboardsV1alphaDashboardMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}


  // MmarshalYaml interface implementation
  func (m *SemaphoreDashboardsV1alphaDashboardMetadata) MarshalYaml() ([]byte, error) {
    return yaml.Marshal(m)
  }

  

  // MmarshalYaml interface implementation
  func (m *SemaphoreDashboardsV1alphaDashboardMetadata) UnmarshalYaml(b []byte) error {
    var res SemaphoreDashboardsV1alphaDashboardMetadata

    err := yaml.UnmarshalStrict(b, &res)

    if err != nil {
      return err
    }

    *m = res
    return nil
  }

  