// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// SemaphoreDashboardsV1alphaDashboardSpecWidget semaphore dashboards v1alpha dashboard spec widget
// swagger:model SemaphoreDashboardsV1alphaDashboardSpecWidget
type SemaphoreDashboardsV1alphaDashboardSpecWidget struct {

	// filters
	Filters map[string]string `json:"filters,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this semaphore dashboards v1alpha dashboard spec widget
func (m *SemaphoreDashboardsV1alphaDashboardSpecWidget) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SemaphoreDashboardsV1alphaDashboardSpecWidget) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SemaphoreDashboardsV1alphaDashboardSpecWidget) UnmarshalBinary(b []byte) error {
	var res SemaphoreDashboardsV1alphaDashboardSpecWidget
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
