// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// SemaphoreDashboardsV1alphaDashboardMetadata semaphore dashboards v1alpha dashboard metadata
// swagger:model SemaphoreDashboardsV1alphaDashboardMetadata
type SemaphoreDashboardsV1alphaDashboardMetadata struct {

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this semaphore dashboards v1alpha dashboard metadata
func (m *SemaphoreDashboardsV1alphaDashboardMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SemaphoreDashboardsV1alphaDashboardMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SemaphoreDashboardsV1alphaDashboardMetadata) UnmarshalBinary(b []byte) error {
	var res SemaphoreDashboardsV1alphaDashboardMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
