// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SemaphoreSecretsV1betaListSecretsResponse semaphore secrets v1beta list secrets response
// swagger:model SemaphoreSecretsV1betaListSecretsResponse
type SemaphoreSecretsV1betaListSecretsResponse struct {

	// next page token
	NextPageToken string `json:"next_page_token,omitempty"`

	// secrets
	Secrets []*SemaphoreSecretsV1betaSecret `json:"secrets"`
}

// Validate validates this semaphore secrets v1beta list secrets response
func (m *SemaphoreSecretsV1betaListSecretsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSecrets(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SemaphoreSecretsV1betaListSecretsResponse) validateSecrets(formats strfmt.Registry) error {

	if swag.IsZero(m.Secrets) { // not required
		return nil
	}

	for i := 0; i < len(m.Secrets); i++ {
		if swag.IsZero(m.Secrets[i]) { // not required
			continue
		}

		if m.Secrets[i] != nil {
			if err := m.Secrets[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("secrets" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SemaphoreSecretsV1betaListSecretsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SemaphoreSecretsV1betaListSecretsResponse) UnmarshalBinary(b []byte) error {
	var res SemaphoreSecretsV1betaListSecretsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
